language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-Xmx2048m"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: mvn verify -B -Dmaven.test.skip=false
